module.exports =  Object.freeze({
    addUser : "addUser",
    userId : "userId",
    videoCall : "videoCall",
    userAlreadyAdded : "userAllReadyAdded",
    videoCallStarted : "videoCallStarted",
    newUserAdded : "newUserAdded",
    failedToJoinVideoCall : "failedToJoinVideoCall",
    notifyUsers : "notifyUsers",
    toUserId : "toUserId",
    fromUserId : "fromUserId",
    startCall : "startCall",
    candidate : "candidate",
    offer : "offer",
    answer : "answer",
    bye : "bye",
    removeUser : "removeUser",
    chat: "chat",
    typing: "typing",
    initiateChat: "initiateChat",
    sendMessage : "sendMessage",
    userStatus : "userStatus",
    online : "Online",
    offline : "Offline",
    sent : "sent",
    messageStatus : "messageStatus",
    delivered : "delivered",
    seen : "seen",
    received : "received",
    test: "test"
});
